Guestbook/Models/CommentSummary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

// View Model = un oggetto model creato allo scopo esclusivo di mostrare dati su schermo

namespace Guestbook.Models
{
    public class CommentSummary
    {
        public string UserName { get; set; }
        public int NumberOfComments { get; set; }
    }
}

Guestbook/Controllers/GuestbookController.cs
using Guestbook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Guestbook.Controllers
{
    public class GuestbookController : Controller
    {
        private IGuestbookRepository _repository;

        public GuestbookController() { // costruttore di default invocato dal framework quando l'applicazione viene eseguita
            _repository = new GuestbookRepository();
        }

        public GuestbookController(IGuestbookRepository repository) // costruttore utilizzato nei test per iniettare un'implementazione fake del repository
        {
            _repository = repository;
        }

        public ActionResult Index()
        {
            //ViewBag.Entries = _repository.GetMostRecentEntries(); // passa il risultato della query alla view
            int i = 5;
            return View(_repository.GetMostRecentEntries());
        }
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(GuestbookEntry entry)
        {
            if(ModelState.IsValid)
            {
                _repository.AddEntry(entry);
                return RedirectToAction("Index"); // redirect all'azione Index()
            }
            return View(entry); // se la validazione dei dati inseriti fallisce torna alla vista di inserimento dove l'utente può correggerli            
        }
       
        public ActionResult Show(int id)
        {
            var entry =_repository.FindById(id); // recupero l'oggetto con l'id specificato
            bool hasPermission = User.Identity.Name == "alex.ruzzante@yahoo.it";//entry.Name;
            ViewBag.HasPermission = hasPermission;
            return View(entry); // lo passo alla View
        }
        public ActionResult CommentSummary()
        {
            return View(_repository.GetCommentSummary());
        }
        public ActionResult Tablesorter()
        {
            return View();
        }
        public ActionResult Edit(int id)
        {
            var entry = _repository.FindById(id);
            return View(entry);
        }
        [HttpPost]
        public ActionResult Edit(GuestbookEntry entry)
        {
            var entryToUpdate = _repository.FindById(entry.Id);
            entryToUpdate.DateAdded = DateTime.Now;
            if (TryUpdateModel(entryToUpdate,
               new string[] { "Name", "Message", "DateAdded" }))
            {
                    _repository.UpdateEntry();
                    return RedirectToAction("Index");
            }
            else
            {
                return View(entryToUpdate);
            }
             // se la validazione dei dati inseriti fallisce torna alla vista di inserimento dove l'utente può correggerli            
        }
    }
}

Guestbook/Views/Guestbook/CommentSummary.cshtml
@model IEnumerable<Guestbook.Models.CommentSummary>

<h2>Comment Summary</h2>
<table>
    <tr>
        <th>Number of comments</th>
        <th>User name</th>
    </tr>
    @foreach(var summaryRow in Model)
    {
        <tr>
            <td>@summaryRow.NumberOfComments</td>
            <td>@summaryRow.UserName</td>
        </tr>
    }
</table>

Guestbook/Views/Guestbook/Create.cshtml
@model Guestbook.Models.GuestbookEntry

<h2>Add new Entry</h2>
@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <p>
        @Html.LabelFor(m => m.Name)
        @Html.EditorFor(m => m.Name) <!-- EditorFor lascia scegliere al framework l'editor più opportuno in base al tipo di dato-->
    </p>
    <p>
        @Html.LabelFor(m => m.Message)
        @Html.EditorFor(m => m.Message)
    </p>
    <p><input type="submit" value="Save" /></p>
}

Guestbook/Views/Guestbook/Edit.cshtml
@model Guestbook.Models.GuestbookEntry

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <p>
        @Html.LabelFor(Model => Model.Name)
        @Html.EditorFor(Model => Model.Name) <!-- EditorFor lascia scegliere al framework l'editor più opportuno in base al tipo di dato-->
    </p>
    <p>
        @Html.LabelFor(Model => Model.Message)
        @Html.EditorFor(Model => Model.Message)
    </p>
    <p><input type="submit" value="Save" /></p>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Guestbook/Views/Guestbook/Index.cshtml
@model IEnumerable<Guestbook.Models.GuestbookEntry>

<h2>My Guestbook Entries</h2>

<p>@Html.ActionLink("Add new Entry", "Create", "Guestbook")</p>
<p>@Html.ActionLink("Comment Summary", "CommentSummary", "Guestbook")</p>
@foreach (var entry in Model) //oppure (var entry in ViewBag.Entries) se uso ViewBag per passare i dati
{
    <section class="contact">
        <header>
            <h3>@Html.ActionLink(entry.Message, "Show", "Guestbook", new { id = entry.Id }, null)</h3>
        </header>
        <p>
            Posted by @entry.Name on @entry.DateAdded.ToLongDateString() at @entry.DateAdded.ToLongTimeString() with id @entry.Id
        </p>
    </section>
}

Guestbook/Views/Guestbook/Show.cshtml
@model Guestbook.Models.GuestbookEntry /* la view è fortemente tipata */

<h2>Guestbook Entry</h2>
<dl>
    <dt>Name:</dt>
    <dd>@Model.Name</dd>
    <dt>Date Added:</dt>
    <dd>@Model.DateAdded</dd>
    <dt>Message:</dt>
    <dd>@Model.Message</dd>
</dl>
    <p>
        @if (ViewBag.hasPermission)
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
        }
        @Html.ActionLink("Back to Entries", "Index")
    </p>

Guestbook/Views/Guestbook/Tablesorter.cshtml
@{
    ViewBag.Title = "Tablesorter";
}

<h2>DataTable</h2>

@section scripts {
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
}
 

<table id="myTable" class="tablesorter table table-striped">
    <thead>
        <tr>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Email</th>
            <th>Due</th>
            <th>Web Site</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Smith</td>
            <td>John</td>
            <td>jsmith@gmail.com</td>
            <td>$50.00</td>
            <td>http://www.jsmith.com</td>
        </tr>
        <tr>
            <td>Bach</td>
            <td>Frank</td>
            <td>fbach@yahoo.com</td>
            <td>$50.00</td>
            <td>http://www.frank.com</td>
        </tr>
        <tr>
            <td>Doe</td>
            <td>Jason</td>
            <td>jdoe@hotmail.com</td>
            <td>$100.00</td>
            <td>http://www.jdoe.com</td>
        </tr>
        <tr>
            <td>Conway</td>
            <td>Tim</td>
            <td>tconway@earthlink.net</td>
            <td>$50.00</td>
            <td>http://www.timconway.com</td>
        </tr>
    </tbody>
</table> 